function defs = method_registry(precInfo)
% METHOD_REGISTRY  Catalog of solver definitions.

    suffix = legend_suffix(precInfo);

    defs(1) = struct( ...
        'name',      'HS-BCG', ...
        'legend',    ['HS-BCG' suffix], ...
        'lineStyle', ':', ...
        'color',     [0.8500 0.3250 0.0980]);

    defs(2) = struct( ...
        'name',      'DP-BCG', ...
        'legend',    ['DP-BCG' suffix], ...
        'lineStyle', '--', ...
        'color',     [0.0000 0.4470 0.7410]);

    defs(3) = struct( ...
        'name',      'DR-BCG', ...
        'legend',    ['DR-BCG' suffix], ...
        'lineStyle', '-', ...
        'color',     [0.0000 0.0000 0.0000]);

    defs(4) = struct( ...
        'name',      'BF-BCG', ...
        'legend',    ['BF-BCG' suffix], ...
        'lineStyle', ':', ...
        'color',     [0.8500 0.3250 0.0980]);

    defs = defs(:);

end

function suffix = legend_suffix(precInfo)
    if ~isfield(precInfo, 'type') || strcmpi(precInfo.type, 'none')
        suffix = '';
        return;
    end

    switch lower(precInfo.type)
        case 'ichol'
            tolTxt = format_scientific(precInfo.opts.droptol);
            suffix = sprintf(' + ICT($%s$)', tolTxt);
        otherwise
            suffix = sprintf(' + %s', upper(precInfo.type));
    end
end
